packages:
  - "apps/*"
  - "packages/*"
  - "agents/*"
allowBuilds:
  '@mongodb-js/zstd': true
  core-js-pure: true
  esbuild: true
  msw: true
  node-liblzma: false
  onnxruntime-node: false
  protobufjs: false
  sharp: true
minimumReleaseAgeExclude:
  - eve@0.67.1
